
    CREATE TRIGGER audit_bodega_insert
    AFTER INSERT ON bodega
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('bodega', USER(), 'INSERT', JSON_OBJECT("ID_BODEGA", NEW.ID_BODEGA, "NOMBRE_BODEGA", NEW.NOMBRE_BODEGA, "UBICACION", NEW.UBICACION, "CAPACIDAD", NEW.CAPACIDAD));
    END;

    CREATE TRIGGER audit_bodega_update
    AFTER UPDATE ON bodega
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('bodega', USER(), 'UPDATE', JSON_OBJECT("ID_BODEGA", NEW.ID_BODEGA, "NOMBRE_BODEGA", NEW.NOMBRE_BODEGA, "UBICACION", NEW.UBICACION, "CAPACIDAD", NEW.CAPACIDAD));
    END;

    CREATE TRIGGER audit_bodega_delete
    AFTER DELETE ON bodega
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('bodega', USER(), 'DELETE', JSON_OBJECT("ID_BODEGA", OLD.ID_BODEGA, "NOMBRE_BODEGA", OLD.NOMBRE_BODEGA, "UBICACION", OLD.UBICACION, "CAPACIDAD", OLD.CAPACIDAD));
    END;
    

    CREATE TRIGGER audit_carrito_compra_insert
    AFTER INSERT ON carrito_compra
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('carrito_compra', USER(), 'INSERT', JSON_OBJECT("ID_CLIENTE", NEW.ID_CLIENTE, "ID_CARRITO_COMPRA", NEW.ID_CARRITO_COMPRA, "ID_PEDIDO", NEW.ID_PEDIDO, "FECHA_CREACION", NEW.FECHA_CREACION, "ESTADO", NEW.ESTADO));
    END;

    CREATE TRIGGER audit_carrito_compra_update
    AFTER UPDATE ON carrito_compra
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('carrito_compra', USER(), 'UPDATE', JSON_OBJECT("ID_CLIENTE", NEW.ID_CLIENTE, "ID_CARRITO_COMPRA", NEW.ID_CARRITO_COMPRA, "ID_PEDIDO", NEW.ID_PEDIDO, "FECHA_CREACION", NEW.FECHA_CREACION, "ESTADO", NEW.ESTADO));
    END;

    CREATE TRIGGER audit_carrito_compra_delete
    AFTER DELETE ON carrito_compra
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('carrito_compra', USER(), 'DELETE', JSON_OBJECT("ID_CLIENTE", OLD.ID_CLIENTE, "ID_CARRITO_COMPRA", OLD.ID_CARRITO_COMPRA, "ID_PEDIDO", OLD.ID_PEDIDO, "FECHA_CREACION", OLD.FECHA_CREACION, "ESTADO", OLD.ESTADO));
    END;
    

    CREATE TRIGGER audit_categoria_empleado_insert
    AFTER INSERT ON categoria_empleado
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('categoria_empleado', USER(), 'INSERT', JSON_OBJECT("ID_CATEGORIA_EMPLEADO", NEW.ID_CATEGORIA_EMPLEADO, "NOMBRE_CATEGORIA", NEW.NOMBRE_CATEGORIA, "SALARIO", NEW.SALARIO, "BENEFICIOS", NEW.BENEFICIOS, "DESCRIPCION", NEW.DESCRIPCION));
    END;

    CREATE TRIGGER audit_categoria_empleado_update
    AFTER UPDATE ON categoria_empleado
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('categoria_empleado', USER(), 'UPDATE', JSON_OBJECT("ID_CATEGORIA_EMPLEADO", NEW.ID_CATEGORIA_EMPLEADO, "NOMBRE_CATEGORIA", NEW.NOMBRE_CATEGORIA, "SALARIO", NEW.SALARIO, "BENEFICIOS", NEW.BENEFICIOS, "DESCRIPCION", NEW.DESCRIPCION));
    END;

    CREATE TRIGGER audit_categoria_empleado_delete
    AFTER DELETE ON categoria_empleado
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('categoria_empleado', USER(), 'DELETE', JSON_OBJECT("ID_CATEGORIA_EMPLEADO", OLD.ID_CATEGORIA_EMPLEADO, "NOMBRE_CATEGORIA", OLD.NOMBRE_CATEGORIA, "SALARIO", OLD.SALARIO, "BENEFICIOS", OLD.BENEFICIOS, "DESCRIPCION", OLD.DESCRIPCION));
    END;
    

    CREATE TRIGGER audit_categoria_producto_insert
    AFTER INSERT ON categoria_producto
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('categoria_producto', USER(), 'INSERT', JSON_OBJECT("ID_CATEGORIA_PRODUCTO", NEW.ID_CATEGORIA_PRODUCTO, "EMBUTIDOS", NEW.EMBUTIDOS));
    END;

    CREATE TRIGGER audit_categoria_producto_update
    AFTER UPDATE ON categoria_producto
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('categoria_producto', USER(), 'UPDATE', JSON_OBJECT("ID_CATEGORIA_PRODUCTO", NEW.ID_CATEGORIA_PRODUCTO, "EMBUTIDOS", NEW.EMBUTIDOS));
    END;

    CREATE TRIGGER audit_categoria_producto_delete
    AFTER DELETE ON categoria_producto
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('categoria_producto', USER(), 'DELETE', JSON_OBJECT("ID_CATEGORIA_PRODUCTO", OLD.ID_CATEGORIA_PRODUCTO, "EMBUTIDOS", OLD.EMBUTIDOS));
    END;
    

    CREATE TRIGGER audit_cliente_insert
    AFTER INSERT ON cliente
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('cliente', USER(), 'INSERT', JSON_OBJECT("ID_CLIENTE", NEW.ID_CLIENTE, "NOMBRE", NEW.NOMBRE, "TELEFONO", NEW.TELEFONO, "CEDULA", NEW.CEDULA, "CORREO", NEW.CORREO));
    END;

    CREATE TRIGGER audit_cliente_update
    AFTER UPDATE ON cliente
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('cliente', USER(), 'UPDATE', JSON_OBJECT("ID_CLIENTE", NEW.ID_CLIENTE, "NOMBRE", NEW.NOMBRE, "TELEFONO", NEW.TELEFONO, "CEDULA", NEW.CEDULA, "CORREO", NEW.CORREO));
    END;

    CREATE TRIGGER audit_cliente_delete
    AFTER DELETE ON cliente
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('cliente', USER(), 'DELETE', JSON_OBJECT("ID_CLIENTE", OLD.ID_CLIENTE, "NOMBRE", OLD.NOMBRE, "TELEFONO", OLD.TELEFONO, "CEDULA", OLD.CEDULA, "CORREO", OLD.CORREO));
    END;
    

    CREATE TRIGGER audit_contrato_insert
    AFTER INSERT ON contrato
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('contrato', USER(), 'INSERT', JSON_OBJECT("ID_CONTRARTO", NEW.ID_CONTRARTO, "FECHA_INICIO_CONTRATO", NEW.FECHA_INICIO_CONTRATO, "FECHA_FIN_CONTRATO", NEW.FECHA_FIN_CONTRATO, "SUELDO", NEW.SUELDO, "TERMINOS", NEW.TERMINOS));
    END;

    CREATE TRIGGER audit_contrato_update
    AFTER UPDATE ON contrato
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('contrato', USER(), 'UPDATE', JSON_OBJECT("ID_CONTRARTO", NEW.ID_CONTRARTO, "FECHA_INICIO_CONTRATO", NEW.FECHA_INICIO_CONTRATO, "FECHA_FIN_CONTRATO", NEW.FECHA_FIN_CONTRATO, "SUELDO", NEW.SUELDO, "TERMINOS", NEW.TERMINOS));
    END;

    CREATE TRIGGER audit_contrato_delete
    AFTER DELETE ON contrato
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('contrato', USER(), 'DELETE', JSON_OBJECT("ID_CONTRARTO", OLD.ID_CONTRARTO, "FECHA_INICIO_CONTRATO", OLD.FECHA_INICIO_CONTRATO, "FECHA_FIN_CONTRATO", OLD.FECHA_FIN_CONTRATO, "SUELDO", OLD.SUELDO, "TERMINOS", OLD.TERMINOS));
    END;
    

    CREATE TRIGGER audit_detalle_factura_insert
    AFTER INSERT ON detalle_factura
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('detalle_factura', USER(), 'INSERT', JSON_OBJECT("ID_DETALLE_FACTURA", NEW.ID_DETALLE_FACTURA, "ID_FACTURA", NEW.ID_FACTURA, "ID_METODO_PAGO", NEW.ID_METODO_PAGO, "CANTIDAD_PRODUCTO", NEW.CANTIDAD_PRODUCTO, "PRECIO_UNITARIO", NEW.PRECIO_UNITARIO, "SUBTOTAL", NEW.SUBTOTAL, "IVA", NEW.IVA));
    END;

    CREATE TRIGGER audit_detalle_factura_update
    AFTER UPDATE ON detalle_factura
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('detalle_factura', USER(), 'UPDATE', JSON_OBJECT("ID_DETALLE_FACTURA", NEW.ID_DETALLE_FACTURA, "ID_FACTURA", NEW.ID_FACTURA, "ID_METODO_PAGO", NEW.ID_METODO_PAGO, "CANTIDAD_PRODUCTO", NEW.CANTIDAD_PRODUCTO, "PRECIO_UNITARIO", NEW.PRECIO_UNITARIO, "SUBTOTAL", NEW.SUBTOTAL, "IVA", NEW.IVA));
    END;

    CREATE TRIGGER audit_detalle_factura_delete
    AFTER DELETE ON detalle_factura
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('detalle_factura', USER(), 'DELETE', JSON_OBJECT("ID_DETALLE_FACTURA", OLD.ID_DETALLE_FACTURA, "ID_FACTURA", OLD.ID_FACTURA, "ID_METODO_PAGO", OLD.ID_METODO_PAGO, "CANTIDAD_PRODUCTO", OLD.CANTIDAD_PRODUCTO, "PRECIO_UNITARIO", OLD.PRECIO_UNITARIO, "SUBTOTAL", OLD.SUBTOTAL, "IVA", OLD.IVA));
    END;
    

    CREATE TRIGGER audit_detalle_producto_insert
    AFTER INSERT ON detalle_producto
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('detalle_producto', USER(), 'INSERT', JSON_OBJECT("ID_DETALLE_PRODUCTO", NEW.ID_DETALLE_PRODUCTO, "COMPOSICION", NEW.COMPOSICION, "FECHA_ELABORACION", NEW.FECHA_ELABORACION, "FECHA_CADUCIDAD", NEW.FECHA_CADUCIDAD, "TAMANO", NEW.TAMANO, "PESO", NEW.PESO, "MODELO", NEW.MODELO));
    END;

    CREATE TRIGGER audit_detalle_producto_update
    AFTER UPDATE ON detalle_producto
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('detalle_producto', USER(), 'UPDATE', JSON_OBJECT("ID_DETALLE_PRODUCTO", NEW.ID_DETALLE_PRODUCTO, "COMPOSICION", NEW.COMPOSICION, "FECHA_ELABORACION", NEW.FECHA_ELABORACION, "FECHA_CADUCIDAD", NEW.FECHA_CADUCIDAD, "TAMANO", NEW.TAMANO, "PESO", NEW.PESO, "MODELO", NEW.MODELO));
    END;

    CREATE TRIGGER audit_detalle_producto_delete
    AFTER DELETE ON detalle_producto
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('detalle_producto', USER(), 'DELETE', JSON_OBJECT("ID_DETALLE_PRODUCTO", OLD.ID_DETALLE_PRODUCTO, "COMPOSICION", OLD.COMPOSICION, "FECHA_ELABORACION", OLD.FECHA_ELABORACION, "FECHA_CADUCIDAD", OLD.FECHA_CADUCIDAD, "TAMANO", OLD.TAMANO, "PESO", OLD.PESO, "MODELO", OLD.MODELO));
    END;
    

    CREATE TRIGGER audit_detallefactura_producto_insert
    AFTER INSERT ON detallefactura_producto
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('detallefactura_producto', USER(), 'INSERT', JSON_OBJECT("ID_PRODUCTO", NEW.ID_PRODUCTO, "ID_DETALLE_FACTURA", NEW.ID_DETALLE_FACTURA));
    END;

    CREATE TRIGGER audit_detallefactura_producto_update
    AFTER UPDATE ON detallefactura_producto
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('detallefactura_producto', USER(), 'UPDATE', JSON_OBJECT("ID_PRODUCTO", NEW.ID_PRODUCTO, "ID_DETALLE_FACTURA", NEW.ID_DETALLE_FACTURA));
    END;

    CREATE TRIGGER audit_detallefactura_producto_delete
    AFTER DELETE ON detallefactura_producto
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('detallefactura_producto', USER(), 'DELETE', JSON_OBJECT("ID_PRODUCTO", OLD.ID_PRODUCTO, "ID_DETALLE_FACTURA", OLD.ID_DETALLE_FACTURA));
    END;
    

    CREATE TRIGGER audit_direccion_entrega_insert
    AFTER INSERT ON direccion_entrega
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('direccion_entrega', USER(), 'INSERT', JSON_OBJECT("ID_DIRECCION_ENTREGA", NEW.ID_DIRECCION_ENTREGA, "NUMERO_TELEFONO", NEW.NUMERO_TELEFONO, "DIRECCION_DE_ENVIO", NEW.DIRECCION_DE_ENVIO));
    END;

    CREATE TRIGGER audit_direccion_entrega_update
    AFTER UPDATE ON direccion_entrega
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('direccion_entrega', USER(), 'UPDATE', JSON_OBJECT("ID_DIRECCION_ENTREGA", NEW.ID_DIRECCION_ENTREGA, "NUMERO_TELEFONO", NEW.NUMERO_TELEFONO, "DIRECCION_DE_ENVIO", NEW.DIRECCION_DE_ENVIO));
    END;

    CREATE TRIGGER audit_direccion_entrega_delete
    AFTER DELETE ON direccion_entrega
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('direccion_entrega', USER(), 'DELETE', JSON_OBJECT("ID_DIRECCION_ENTREGA", OLD.ID_DIRECCION_ENTREGA, "NUMERO_TELEFONO", OLD.NUMERO_TELEFONO, "DIRECCION_DE_ENVIO", OLD.DIRECCION_DE_ENVIO));
    END;
    

    CREATE TRIGGER audit_empleado_insert
    AFTER INSERT ON empleado
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('empleado', USER(), 'INSERT', JSON_OBJECT("ID_EMPLEADO", NEW.ID_EMPLEADO, "ID_CATEGORIA_EMPLEADO", NEW.ID_CATEGORIA_EMPLEADO, "ID_CONTRATO", NEW.ID_CONTRATO, "NOMBRE_EMPLEADO", NEW.NOMBRE_EMPLEADO, "FECHA_CONTRATACION", NEW.FECHA_CONTRATACION, "FECHA_NACIMIENTO", NEW.FECHA_NACIMIENTO, "CONTACTO", NEW.CONTACTO));
    END;

    CREATE TRIGGER audit_empleado_update
    AFTER UPDATE ON empleado
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('empleado', USER(), 'UPDATE', JSON_OBJECT("ID_EMPLEADO", NEW.ID_EMPLEADO, "ID_CATEGORIA_EMPLEADO", NEW.ID_CATEGORIA_EMPLEADO, "ID_CONTRATO", NEW.ID_CONTRATO, "NOMBRE_EMPLEADO", NEW.NOMBRE_EMPLEADO, "FECHA_CONTRATACION", NEW.FECHA_CONTRATACION, "FECHA_NACIMIENTO", NEW.FECHA_NACIMIENTO, "CONTACTO", NEW.CONTACTO));
    END;

    CREATE TRIGGER audit_empleado_delete
    AFTER DELETE ON empleado
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('empleado', USER(), 'DELETE', JSON_OBJECT("ID_EMPLEADO", OLD.ID_EMPLEADO, "ID_CATEGORIA_EMPLEADO", OLD.ID_CATEGORIA_EMPLEADO, "ID_CONTRATO", OLD.ID_CONTRATO, "NOMBRE_EMPLEADO", OLD.NOMBRE_EMPLEADO, "FECHA_CONTRATACION", OLD.FECHA_CONTRATACION, "FECHA_NACIMIENTO", OLD.FECHA_NACIMIENTO, "CONTACTO", OLD.CONTACTO));
    END;
    

    CREATE TRIGGER audit_factura_insert
    AFTER INSERT ON factura
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('factura', USER(), 'INSERT', JSON_OBJECT("ID_FACTURA", NEW.ID_FACTURA, "ID_CLIENTE", NEW.ID_CLIENTE, "ID_PROMOCION", NEW.ID_PROMOCION, "ID_EMPLEADO", NEW.ID_EMPLEADO, "FECHA_EMISION", NEW.FECHA_EMISION, "TOTAL", NEW.TOTAL));
    END;

    CREATE TRIGGER audit_factura_update
    AFTER UPDATE ON factura
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('factura', USER(), 'UPDATE', JSON_OBJECT("ID_FACTURA", NEW.ID_FACTURA, "ID_CLIENTE", NEW.ID_CLIENTE, "ID_PROMOCION", NEW.ID_PROMOCION, "ID_EMPLEADO", NEW.ID_EMPLEADO, "FECHA_EMISION", NEW.FECHA_EMISION, "TOTAL", NEW.TOTAL));
    END;

    CREATE TRIGGER audit_factura_delete
    AFTER DELETE ON factura
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('factura', USER(), 'DELETE', JSON_OBJECT("ID_FACTURA", OLD.ID_FACTURA, "ID_CLIENTE", OLD.ID_CLIENTE, "ID_PROMOCION", OLD.ID_PROMOCION, "ID_EMPLEADO", OLD.ID_EMPLEADO, "FECHA_EMISION", OLD.FECHA_EMISION, "TOTAL", OLD.TOTAL));
    END;
    

    CREATE TRIGGER audit_metodo_pago_insert
    AFTER INSERT ON metodo_pago
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('metodo_pago', USER(), 'INSERT', JSON_OBJECT("ID_METODO_PAGO", NEW.ID_METODO_PAGO, "TARJETA", NEW.TARJETA, "EFECTIVO", NEW.EFECTIVO, "TRANSFERENCIA", NEW.TRANSFERENCIA));
    END;

    CREATE TRIGGER audit_metodo_pago_update
    AFTER UPDATE ON metodo_pago
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('metodo_pago', USER(), 'UPDATE', JSON_OBJECT("ID_METODO_PAGO", NEW.ID_METODO_PAGO, "TARJETA", NEW.TARJETA, "EFECTIVO", NEW.EFECTIVO, "TRANSFERENCIA", NEW.TRANSFERENCIA));
    END;

    CREATE TRIGGER audit_metodo_pago_delete
    AFTER DELETE ON metodo_pago
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('metodo_pago', USER(), 'DELETE', JSON_OBJECT("ID_METODO_PAGO", OLD.ID_METODO_PAGO, "TARJETA", OLD.TARJETA, "EFECTIVO", OLD.EFECTIVO, "TRANSFERENCIA", OLD.TRANSFERENCIA));
    END;
    

    CREATE TRIGGER audit_pasillo_insert
    AFTER INSERT ON pasillo
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('pasillo', USER(), 'INSERT', JSON_OBJECT("ID_PASILLO", NEW.ID_PASILLO, "NUM_PASILLO", NEW.NUM_PASILLO, "NOMBRE_PASILLO", NEW.NOMBRE_PASILLO));
    END;

    CREATE TRIGGER audit_pasillo_update
    AFTER UPDATE ON pasillo
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('pasillo', USER(), 'UPDATE', JSON_OBJECT("ID_PASILLO", NEW.ID_PASILLO, "NUM_PASILLO", NEW.NUM_PASILLO, "NOMBRE_PASILLO", NEW.NOMBRE_PASILLO));
    END;

    CREATE TRIGGER audit_pasillo_delete
    AFTER DELETE ON pasillo
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('pasillo', USER(), 'DELETE', JSON_OBJECT("ID_PASILLO", OLD.ID_PASILLO, "NUM_PASILLO", OLD.NUM_PASILLO, "NOMBRE_PASILLO", OLD.NOMBRE_PASILLO));
    END;
    

    CREATE TRIGGER audit_pedido_insert
    AFTER INSERT ON pedido
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('pedido', USER(), 'INSERT', JSON_OBJECT("ID_PEDIDO", NEW.ID_PEDIDO, "ID_DIRECCION_ENTREGA", NEW.ID_DIRECCION_ENTREGA, "ESTADO_ENTREGA", NEW.ESTADO_ENTREGA, "FECHA_ENVIO", NEW.FECHA_ENVIO));
    END;

    CREATE TRIGGER audit_pedido_update
    AFTER UPDATE ON pedido
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('pedido', USER(), 'UPDATE', JSON_OBJECT("ID_PEDIDO", NEW.ID_PEDIDO, "ID_DIRECCION_ENTREGA", NEW.ID_DIRECCION_ENTREGA, "ESTADO_ENTREGA", NEW.ESTADO_ENTREGA, "FECHA_ENVIO", NEW.FECHA_ENVIO));
    END;

    CREATE TRIGGER audit_pedido_delete
    AFTER DELETE ON pedido
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('pedido', USER(), 'DELETE', JSON_OBJECT("ID_PEDIDO", OLD.ID_PEDIDO, "ID_DIRECCION_ENTREGA", OLD.ID_DIRECCION_ENTREGA, "ESTADO_ENTREGA", OLD.ESTADO_ENTREGA, "FECHA_ENVIO", OLD.FECHA_ENVIO));
    END;
    

    CREATE TRIGGER audit_producto_insert
    AFTER INSERT ON producto
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('producto', USER(), 'INSERT', JSON_OBJECT("ID_PRODUCTO", NEW.ID_PRODUCTO, "ID_PROVEEDOR", NEW.ID_PROVEEDOR, "ID_CATEGORIA_PRODUCTO", NEW.ID_CATEGORIA_PRODUCTO, "NOMBRE_PRODUCTO", NEW.NOMBRE_PRODUCTO, "DESCRIPCION_PRODUCTO", NEW.DESCRIPCION_PRODUCTO, "PRECIO_PRODUCTO", NEW.PRECIO_PRODUCTO, "STOCK", NEW.STOCK));
    END;

    CREATE TRIGGER audit_producto_update
    AFTER UPDATE ON producto
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('producto', USER(), 'UPDATE', JSON_OBJECT("ID_PRODUCTO", NEW.ID_PRODUCTO, "ID_PROVEEDOR", NEW.ID_PROVEEDOR, "ID_CATEGORIA_PRODUCTO", NEW.ID_CATEGORIA_PRODUCTO, "NOMBRE_PRODUCTO", NEW.NOMBRE_PRODUCTO, "DESCRIPCION_PRODUCTO", NEW.DESCRIPCION_PRODUCTO, "PRECIO_PRODUCTO", NEW.PRECIO_PRODUCTO, "STOCK", NEW.STOCK));
    END;

    CREATE TRIGGER audit_producto_delete
    AFTER DELETE ON producto
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('producto', USER(), 'DELETE', JSON_OBJECT("ID_PRODUCTO", OLD.ID_PRODUCTO, "ID_PROVEEDOR", OLD.ID_PROVEEDOR, "ID_CATEGORIA_PRODUCTO", OLD.ID_CATEGORIA_PRODUCTO, "NOMBRE_PRODUCTO", OLD.NOMBRE_PRODUCTO, "DESCRIPCION_PRODUCTO", OLD.DESCRIPCION_PRODUCTO, "PRECIO_PRODUCTO", OLD.PRECIO_PRODUCTO, "STOCK", OLD.STOCK));
    END;
    

    CREATE TRIGGER audit_producto_bodega_insert
    AFTER INSERT ON producto_bodega
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('producto_bodega', USER(), 'INSERT', JSON_OBJECT("ID_BODEGA", NEW.ID_BODEGA, "ID_PRODUCTO", NEW.ID_PRODUCTO, "CANTIDAD_PRODUCTOBODEGA", NEW.CANTIDAD_PRODUCTOBODEGA, "FECHA_ENTRADA_BODEGA", NEW.FECHA_ENTRADA_BODEGA, "FECHA_SALIDA", NEW.FECHA_SALIDA));
    END;

    CREATE TRIGGER audit_producto_bodega_update
    AFTER UPDATE ON producto_bodega
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('producto_bodega', USER(), 'UPDATE', JSON_OBJECT("ID_BODEGA", NEW.ID_BODEGA, "ID_PRODUCTO", NEW.ID_PRODUCTO, "CANTIDAD_PRODUCTOBODEGA", NEW.CANTIDAD_PRODUCTOBODEGA, "FECHA_ENTRADA_BODEGA", NEW.FECHA_ENTRADA_BODEGA, "FECHA_SALIDA", NEW.FECHA_SALIDA));
    END;

    CREATE TRIGGER audit_producto_bodega_delete
    AFTER DELETE ON producto_bodega
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('producto_bodega', USER(), 'DELETE', JSON_OBJECT("ID_BODEGA", OLD.ID_BODEGA, "ID_PRODUCTO", OLD.ID_PRODUCTO, "CANTIDAD_PRODUCTOBODEGA", OLD.CANTIDAD_PRODUCTOBODEGA, "FECHA_ENTRADA_BODEGA", OLD.FECHA_ENTRADA_BODEGA, "FECHA_SALIDA", OLD.FECHA_SALIDA));
    END;
    

    CREATE TRIGGER audit_promociones_insert
    AFTER INSERT ON promociones
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('promociones', USER(), 'INSERT', JSON_OBJECT("ID_PROMOCION", NEW.ID_PROMOCION, "TIPO_PROM", NEW.TIPO_PROM, "FECHA_INICIO", NEW.FECHA_INICIO, "FECHA_FIN", NEW.FECHA_FIN));
    END;

    CREATE TRIGGER audit_promociones_update
    AFTER UPDATE ON promociones
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('promociones', USER(), 'UPDATE', JSON_OBJECT("ID_PROMOCION", NEW.ID_PROMOCION, "TIPO_PROM", NEW.TIPO_PROM, "FECHA_INICIO", NEW.FECHA_INICIO, "FECHA_FIN", NEW.FECHA_FIN));
    END;

    CREATE TRIGGER audit_promociones_delete
    AFTER DELETE ON promociones
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('promociones', USER(), 'DELETE', JSON_OBJECT("ID_PROMOCION", OLD.ID_PROMOCION, "TIPO_PROM", OLD.TIPO_PROM, "FECHA_INICIO", OLD.FECHA_INICIO, "FECHA_FIN", OLD.FECHA_FIN));
    END;
    

    CREATE TRIGGER audit_proveedor_insert
    AFTER INSERT ON proveedor
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('proveedor', USER(), 'INSERT', JSON_OBJECT("ID_PROVEEDOR", NEW.ID_PROVEEDOR, "NOMBRE_PROVEEDOR", NEW.NOMBRE_PROVEEDOR, "CEDULA_PROVEEDOR", NEW.CEDULA_PROVEEDOR, "NUMERO_TELEFONO", NEW.NUMERO_TELEFONO));
    END;

    CREATE TRIGGER audit_proveedor_update
    AFTER UPDATE ON proveedor
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('proveedor', USER(), 'UPDATE', JSON_OBJECT("ID_PROVEEDOR", NEW.ID_PROVEEDOR, "NOMBRE_PROVEEDOR", NEW.NOMBRE_PROVEEDOR, "CEDULA_PROVEEDOR", NEW.CEDULA_PROVEEDOR, "NUMERO_TELEFONO", NEW.NUMERO_TELEFONO));
    END;

    CREATE TRIGGER audit_proveedor_delete
    AFTER DELETE ON proveedor
    FOR EACH ROW
    BEGIN
        INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
        VALUES ('proveedor', USER(), 'DELETE', JSON_OBJECT("ID_PROVEEDOR", OLD.ID_PROVEEDOR, "NOMBRE_PROVEEDOR", OLD.NOMBRE_PROVEEDOR, "CEDULA_PROVEEDOR", OLD.CEDULA_PROVEEDOR, "NUMERO_TELEFONO", OLD.NUMERO_TELEFONO));
    END;
    
